### ISSUE TITLE
请问群消息塔罗牌图片发送不出去是什么原因呢

### ISSUE THREAD

**Issue by snowluvletter** [liuly0322/l-plugin#9]
错误信息是：YzBot][11:34:05.552][WARN] 图片1失败, reason: read ECONNRESET

**Comment by liuly0322** [comment]
用的是 https://fastly.jsdelivr.net/ 的 github 下载服务（因为图片资源比较大，不太适合仓库自带），可能是网络原因导致无法访问，后续会考虑添加手动下载

**Comment by snowluvletter** [comment]
试了15次  失败8次  整体比之前好多了  之前十次也就一两次可以，估计是因为我在四川的原因  距离服务器太远了

**Comment by liuly0322** [comment]
更新了 README，现在可以手动下载全部资源到服务器
